language: c
dist: xenial
git:
  depth: false
  quiet: true

env:
  - BSP_PATH="$HOME/.arduino15/packages/adafruit/hardware/nrf52"
  
addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
  snaps:
    - name: ubuntu-make
      confinement: classic

install:
  - pip3 install --user adafruit-nrfutil
  - umake electronics arduino $HOME/arduino_ide
  - export PATH=$HOME/arduino_ide:$PATH
  - arduino --pref "boardsmanager.additional.urls=https://adafruit.github.io/arduino-board-index/package_adafruit_index.json" --save-prefs
  # Install BSP for tools, then remove and create symlink the git code
  - arduino --install-boards adafruit:nrf52
  - BSP_VERSION=`eval ls $BSP_PATH`
  - rm -r $BSP_PATH/*
  - ln -s $TRAVIS_BUILD_DIR $BSP_PATH/$BSP_VERSION
  - arduino --install-library "Adafruit NeoPixel","Adafruit NeoMatrix","Adafruit GFX Library","Adafruit SSD1306","MIDI Library","Adafruit ILI9341","Adafruit HX8357 Library"

before_script:
  
script:
  - python3 tools/build_all.py
