sudo: required
language: c
dist: xenial
git:
  depth: false
  quiet: true

env:
  global:
    - BSP_PATH="$HOME/.arduino15/packages/adafruit/hardware/nrf52"
  jobs:
    # empty env required, else allow_failures will SILENTY IGNORE matching against env...
    -

jobs:
  fast_finish: true
  include:
    - name: "Feather 52840"
      env:  VARIANT="feather52840"
    - name: "Feather 52840 (All warnings)"
      env:  ALL_WARNINGS="true" VARIANT="feather52840"
    - name: "Circuit Playground 52840"
      env:  VARIANT="cplaynrf52840"
    - name: "Circuit Playground 52840 (All warnings)"
      env:  ALL_WARNINGS="true" VARIANT="cplaynrf52840"
    - name: "Feather 52832"
      env:  VARIANT="feather52832"
    - name: "Feather 52832 (All warnings)"
      env:  ALL_WARNINGS="true" VARIANT="feather52832"
  allow_failures:
    - env:  ALL_WARNINGS="true" VARIANT="feather52840"
    - env:  ALL_WARNINGS="true" VARIANT="cplaynrf52840"
    - env:  ALL_WARNINGS="true" VARIANT="feather52832"
    
addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
  snaps:
    - name: ubuntu-make
      confinement: classic

install:
  # Filter only mDNS / Bonjour traffic
  - sudo iptables --insert INPUT  --jump DROP --protocol udp --dport 5353  -m comment --comment "silently drop all 5353/udp input"
  - sudo iptables --insert INPUT  --jump DROP --destination 224.0.0.251    -m comment --comment "silently drop all mDNS ipv4 broadcast"
  # Install the nRF52 support files for arduino
  - pip3 install --user adafruit-nrfutil
  - umake electronics arduino $HOME/arduino_ide
  - export PATH=$HOME/arduino_ide:$PATH
  - arduino --pref "boardsmanager.additional.urls=https://adafruit.github.io/arduino-board-index/package_adafruit_index.json" --save-prefs
  # Install BSP for tools, then remove and create symlink the git code
  - arduino --install-boards adafruit:nrf52
  - BSP_VERSION=`eval ls $BSP_PATH`
  - rm -r $BSP_PATH/*
  - ln -s $TRAVIS_BUILD_DIR $BSP_PATH/$BSP_VERSION
  - arduino --install-library "Adafruit NeoPixel","Adafruit NeoMatrix","Adafruit GFX Library","Adafruit SSD1306","MIDI Library","Adafruit ILI9341","Adafruit HX8357 Library","Adafruit Circuit Playground"

before_script:
  
script:
  - python3 tools/build_all.py
