name: Build

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arduino-platform:
        # Alphabetical order
        - 'cluenrf52840'
        - 'cplaynrf52840'
        - 'feather52832'
        - 'feather52840'
        - 'feather52840sense'
        - 'itsybitsy52840'
        - 'ledglasses_nrf52840'
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        
    - name: Install Arduino CLI and Tools
      run: |
        pip3 install adafruit-nrfutil
        # make all our directories we need for files and libraries
        mkdir $HOME/.arduino15
        mkdir $HOME/.arduino15/packages
        mkdir $HOME/Arduino
        mkdir $HOME/Arduino/libraries
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
        
    - name: Install BSP and Libraries
      env:
        BSP_URL: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
        BSP_PATH: .arduino15/packages/adafruit/hardware/nrf52
      run: |
        arduino-cli config init
        arduino-cli core update-index
        arduino-cli core update-index --additional-urls $BSP_URL
        arduino-cli core install adafruit:nrf52 --additional-urls $BSP_URL

        # Repalce release BSP with our code
        BSP_VERSION=`eval ls $HOME/$BSP_PATH`
        rm -r $HOME/$BSP_PATH/*
        ln -s $GITHUB_WORKSPACE $HOME/$BSP_PATH/$BSP_VERSION

        # Install library dependency
        arduino-cli lib install "Adafruit AHRS" "Adafruit APDS9960 Library" "Adafruit Arcada Library" "Adafruit BMP280 Library" "Adafruit Circuit Playground" "Adafruit EPD" "Adafruit GFX Library" "Adafruit HX8357 Library" "Adafruit ILI9341" "Adafruit LIS3MDL" "Adafruit LSM6DS" "Adafruit NeoPixel" "Adafruit NeoMatrix" "Adafruit Sensor Calibration" "Adafruit SHT31 Library" "Adafruit SSD1306" "Adafruit ST7735 and ST7789 Library" "SdFat - Adafruit Fork"
        arduino-cli lib install "MIDI Library" "Firmata"
        
        # Arduino_TensorFlowLite is removed per maintainer request https://github.com/arduino/library-registry/pull/1748
        # Find a way to compile later, skip TFL example for now
        # arduino-cli lib install "Arduino_TensorFlowLite" 

        # Library summary
        arduino-cli lib list

    - name: Build examples
      run: python3 tools/build_all.py ${{ matrix.arduino-platform }}
