name: Build

on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform: ["feather52840"]

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive      
        
    - name: Install Arduino CLI and Tools
      run: |
        pip3 install --user adafruit-nrfutil
        # make all our directories we need for files and libraries
        mkdir $HOME/.arduino15
        mkdir $HOME/.arduino15/packages
        mkdir $HOME/Arduino
        mkdir $HOME/Arduino/libraries
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        echo "::add-path::$GITHUB_WORKSPACE/bin"
        
    - name: Install BSP and Libraries
      env:
        BSP_URL: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
      run: |
        arduino-cli config init
        arduino-cli core update-index
        arduino-cli core update-index --additional-urls $BSP_URL
        arduino-cli core install adafruit:nrf52 --additional-urls $BSP_URL
        BSP_PATH=$HOME/.arduino15/packages/adafruit/hardware/nrf52
        BSP_VERSION=`eval ls $BSP_PATH`
        rm -r $BSP_PATH/*
        ln -s $GITHUB_WORKSPACE $BSP_PATH/$BSP_VERSION
        arduino-cli lib install "Adafruit NeoPixel" "Adafruit NeoMatrix" "Adafruit GFX Library" "Adafruit SSD1306" "MIDI Library" "Adafruit ILI9341" "Adafruit HX8357 Library" "Adafruit Circuit Playground"

    - name: Build examples
      run: python3 $(GITHUB_WORKSPACE)/build_all.py ${{ matrix.arduino-platform }}
      
    - name: Failed on purpose
      run: exit 1
